# Generated by Django 3.2.3 on 2021-09-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_alter_admin_reg_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Questions', models.CharField(max_length=500)),
                ('Category', models.CharField(max_length=30)),
                ('Option_A', models.CharField(max_length=20)),
                ('Option_B', models.CharField(max_length=20)),
                ('Option_C', models.CharField(max_length=20)),
                ('Option_D', models.CharField(max_length=20)),
                ('Answer', models.CharField(max_length=20)),
            ],
        ),
    ]
